---
title: "DS 2003 Project | Group 10"
author: "Gabe Silverstein"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
library(tidyverse)
```

```{r}
ds_courses <- read_excel("ds_courses.xlsx"); ds_courses
```

```{r}
# filter for undergrad
ds_courses <- filter(ds_courses, `Catalog Number` < 5000); ds_courses 
```

```{r}
# select relevant columns for all questions
ds_courses <- select(ds_courses, `Catalog Number`, `Class Title`, `Primary Instructor Name`, 
                     `Course GPA`, `# of Students`, `A+`, A); ds_courses
```


```{r}
# Q1
prof_gpas <- ds_courses %>% select(`Primary Instructor Name`, `Course GPA`) %>%     
  group_by(`Primary Instructor Name`) %>%
  summarize(avg_gpa = mean(`Course GPA`)) %>% arrange(desc(avg_gpa)); prof_gpas

prof_order <- fct_rev(factor(prof_gpas$`Primary Instructor Name`, 
                             levels=prof_gpas$`Primary Instructor Name`)); prof_order

prof_order_plot <- factor(ds_courses$`Primary Instructor Name`, levels=prof_order)

ggplot(ds_courses, aes(x=`Course GPA`, y=fct_rev(prof_order_plot))) + 
  geom_boxplot() + stat_summary(fun=mean, geom="point", shape=20, size=2, color="red") + 
  labs(title="Professor vs Associated Course GPA",
       y="Primary Instructor Name",
       caption="A comparison of DS Professors and their associated course gpa in the past 3 years.
       The red dots mark the average associated gpa for that professor.")

```


```{r}
# Q2
grpd_courses <- ds_courses %>% select(`Class Title`, `# of Students`, `A+`, A) %>% 
  group_by(`Class Title`) %>% summarize(
    avg_stud = mean(`# of Students`), 
    `avg_A+` = mean(`A+`),
    avg_A = mean(A)); grpd_courses

prob_A <- (grpd_courses$avg_A + grpd_courses$`avg_A+`) / grpd_courses$avg_stud; prob_A

grpd_courses <- grpd_courses %>% mutate(prob_A) %>% arrange(desc(prob_A)); grpd_courses

classes <- fct_rev(factor(grpd_courses$`Class Title`, levels=grpd_courses$`Class Title`))

Category <- c("Domain Elective or Final Project", "Analytics", "N/A", "Foundational Programming", "Systems", "Data Design or Value", "N/A", "Analytics", "Data Design or Value")

ggplot(grpd_courses %>% mutate(Category), aes(x=prob_A, y=classes, fill=Category)) + geom_col() + xlim(0, 1) +
  theme_gray(base_size = 10) + geom_text(aes(label=format(round(prob_A, 2), nsmall = 2)), hjust=1.2) +
  labs(title="DS Course vs Respective Probability of A/A+",
      x="Probability of A or A+",
      y="Class Title",
      caption="A chart demonstrating the association between a particular undergraduate DS course
      and the probability of a student obtaining an A or A+ in it.")

```


```{r}
# Q3
# 3.1
gpa_vs_size <- ds_courses %>%
  group_by(`Primary Instructor Name`) %>%
  summarize(avg_gpa = mean(`Course GPA`),
            avg_size = mean(`# of Students`))

# Plotting
ggplot(gpa_vs_size, aes(x=avg_gpa, y=avg_size)) +
  geom_point(size = 3,aes(color=`Primary Instructor Name`)) +
  labs(x = "Average Class GPA", y = "Average Class Size", title = "Relationship between Average Class GPA and Average Class Size by Instructor", caption="A plot demonstrating the correlation between the average size and average GPA of a course, across different instructors.")
```
```{r}
# 3.2
gpa_vs_size_2 <- ds_courses %>%
  filter(`# of Students` > 10) %>%
  group_by(`Primary Instructor Name`) %>%
  summarize(avg_gpa = mean(`Course GPA`),
            avg_size = mean(`# of Students`))

# Plotting
ggplot(gpa_vs_size_2, aes(x=avg_gpa, y=avg_size)) +
  geom_point(size = 3,aes(color=`Primary Instructor Name`)) +
  labs(x = "Average Class GPA", y = "Average Class Size", title = "Relationship between Average Class GPA and Average Class Size by Instructor", caption="A plot demonstrating the correlation between the average size and average GPA of a course, across different instructors, 
       where class size > 20.")
```


```{r}
# Q4
all_courses <- read_excel("all_courses.xlsx"); all_courses
```

```{r}
# select relevant columns for q4 and combine subject and catalog num
all_courses <- select(all_courses, `Subject`, `Catalog Number`, `Course GPA`); 
all_courses <- unite(all_courses, Course, Subject,`Catalog Number`, sep=" ", remove=FALSE)
all_courses
```

```{r}
Fundamental = c("CS 1110", "CS 1111", "CS 1112", "CS 2110", "PHYS 1655", "CS 1113")
Analytics = c("CS 4774", "PSYC 5710", "STAT 5630")
Systems = c("CS 4750", "COMM 3220", "SYS 2202")
DesignValue = c("SARC 5400", "APMA 2500", "COMM 3810", "COMM 4520", "LPPP 4210", 
                "NASC 4200", "NUIP 3311", "LPPS 5360", "STS 4600", "NUIP 4311")
DomainFinal = c("BME 3636", "CHE 4561", "COMM 4351", "COMM 4230", "COMM 4520", "COMM 4522",
                "CS 3710", "CS 4501", "ENGL 3500", "EVSC 3020", "EVSC 4080", "EVSC 5040",
                "GSVS 4100", "PHS 3102", "STAT 4220", "STAT 4630", "STAT 4800", "STAT 4996")
```

```{r}
# filter out irrelevant courses
all_courses <- filter(all_courses, substr(Course,1,2)=="DS" | match(Course, Fundamental)
                      | match(Course, Analytics) | match(Course, Systems)
                      | match(Course, DesignValue) | match(Course, DomainFinal))
all_courses
```

```{r}
# create new column for category
all_courses <- mutate(all_courses, Category = case_when(
  Course %in% Fundamental | Course=="DS 1002" ~ "Foundational",
  Course %in% Analytics | Course=="DS 2006" | Course=="DS 3001" | Course=="DS 3005"
  | Course=="DS 3006" ~ "Analytics",
  Course %in% Systems | Course=="DS 2002" ~ "Systems",
  Course %in% DesignValue | Course=="DS 2003" | Course=="DS 2004" ~ "Design/Value",
  Course %in% DomainFinal | Course=="DS 4002" ~ "Domain/Final"
)) %>% drop_na(Category);
all_courses
```

```{r}
# mark ds courses
all_courses <- mutate(all_courses, `Class Type` = if_else(substr(Course,1,2)=="DS", "DS Class", "Non-DS Class"))
all_courses
```

```{r}
ggplot(all_courses, aes(fill=`Class Type`, y=`Course GPA`, x=Category)) + 
  geom_boxplot() + labs(title="Course GPA Difference Between DS and non-DS Courses \nGrouped By Requirement Categories", caption="A box plot demonstrating the difference in grade distribution for DS and equivalent\n non-DS classes for each requirement category")
```

```{r}
ggplot(all_courses, aes(fill=`Class Type`, x=`Course GPA`, y=fct_rev(Subject))) + 
  geom_boxplot() + ggtitle("Course GPA Difference Between DS and non-DS Courses \nGrouped By Course Subjects") + labs(caption="A box plot demonstrating the difference in grade distribution for DS and equivalent \nnon-DS for each subject") + ylab("Subject")
```